name: KeepWhiteSpace - Workflow (Moussa Montassar)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  premier-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node
        id: node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: npm
          cache-dependency-path: site/KeepWhiteSpace/package-lock.json  

      - name: Installation
        id: install
        working-directory: site/KeepWhiteSpace
        run: npm ci

      - name: Test des vulnérabilités
        id: audit
        working-directory: site/KeepWhiteSpace
        run: npm audit && echo "Aucune vulnérabilité, tout est ok ! 👌"

      - name: Lancement du ESLint
        id: lint
        working-directory: site/KeepWhiteSpace
        continue-on-error: true 
        run: npm run lint && echo "Vérification du code effectuée avec succès ✅"


      - name: Notif Discord en cas d'erreur
        id: discord
        if: failure()
        uses: appleboy/discord-action@v1.2.0
        with:

          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}

          message: |
            🚒 Le workflow a échoué sur

            🗄️ Repository : ${{ github.repository }}

            🗿 Auteur : ${{ github.actor }}

            🪾 Branche : ${{ github.ref_name }}

            💬 Commit : ${{ github.event.head_commit.message }}

            [Voir le commit](${{ github.event.head_commit.url }})

            ${{ secrets.GIF }}

      - name: Notification Telegram en cas d'erreur
        id: telegram
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_API }}
          message: |
            🚒 Le workflow a échoué sur

            🗄️ Repository : ${{ github.repository }}

            🗿 Auteur : ${{ github.actor }}

            🪾 Branche : ${{ github.ref_name }}

            💬 Commit : ${{ github.event.head_commit.message }}

            [Voir le commit](${{ github.event.head_commit.url }})


  



      - name: Retour des résultats
        if: always()
        run: |
            
            echo "# 🕹️ Projet W@C - JeuxVideOPS" >> $GITHUB_STEP_SUMMARY
            echo "---" >> $GITHUB_STEP_SUMMARY
            echo "## ℹ️ Informations sur le workflow" >> $GITHUB_STEP_SUMMARY
            echo "---" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "![Image](https://i.ibb.co/0jXQy0jT/soutien-2.png)" >> $GITHUB_STEP_SUMMARY
            echo "Le Jeu utiliser pour le projet est Keep White Space [GitHub](https://github.com/okzaq/js-game-keep-white-space)" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "- **Repository** : ${{ github.repository }} [Voir le repository](${{ github.event.repository.html_url }})" >> $GITHUB_STEP_SUMMARY
            echo "- **Auteur** : ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
            echo "- **Branche** : ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
            echo "- **Commit** : ${{ github.event.head_commit.message }} [Voir le commit](${{ github.event.head_commit.url }})" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "---" >> $GITHUB_STEP_SUMMARY
            echo ""
            echo "## Résultats des étapes" >> $GITHUB_STEP_SUMMARY
            echo "- **checkout** : ${{ steps.checkout.outcome }}" >> $GITHUB_STEP_SUMMARY
            echo "- **node** : ${{ steps.node.outcome }}" >> $GITHUB_STEP_SUMMARY
            echo "- **install** : ${{ steps.install.outcome }}" >> $GITHUB_STEP_SUMMARY
            echo "- **audit** : ${{ steps.audit.outcome }}" >> $GITHUB_STEP_SUMMARY
            echo "- **lint** : ${{ steps.lint.outcome }}" >> $GITHUB_STEP_SUMMARY
            echo "- **discord** : ${{ steps.discord.outcome }}" >> ${GITHUB_STEP_SUMMARY}
            echo "- **telegram** : ${{ steps.telegram.outcome }}" >> ${GITHUB_STEP_SUMMARY}
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "---" >> $GITHUB_STEP_SUMMARY
            echo ""
            echo "## Les Fails" >> $GITHUB_STEP_SUMMARY
            echo "***_En cours d'application_***" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "![Image](https://cdn.pixabay.com/animation/2025/09/06/21/34/21-34-47-638_512.gif)" >> $GITHUB_STEP_SUMMARY




  deploy:
    needs: premier-job
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurer Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


            
