name: KeepWhiteSpace - Workflow (Moussa Montassar)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  premier-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: npm

      - name: Installation
        run: npm ci

      - name: Test des vulnérabilités
        run: npm audit && echo "Aucune vulnérabilité, tout est ok ! 👌"

      - name: Lancement du ESLint
        run: npm run lint && echo "Vérification du code effectuée avec succès ✅"

      - name: Notif Discord en cas d'erreur
        if: failure()
        env:
          REPO: ${{ github.repository }}
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          URL: ${{ github.event.head_commit.url }}
          ACTOR: ${{ github.actor }}
          BRANCH: ${{ github.ref_name }}
          COMMIT: ${{ github.event.head_commit.message }}
          IMAGE : "https://media1.tenor.com/m/Q0uNGRsz5cIAAAAC/keyboard-crasher-angry.gif"
        run: |
          MESSAGE="🚒 Le workflow a échoué sur $REPO\n Auteur : $ACTOR\n Branche : $BRANCH\n Commit : $COMMIT\n $URL \n $IMAGE"
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$(printf '{"content": "%s", "image": "%s"}' "$MESSAGE" "$IMAGE")" \
               "$WEBHOOK"
