name: KeepWhiteSpace - Workflow (Moussa Montassar)

on:                                                                                                              
    push:         
      branches:
        - '**'
    pull_request:
      branches:
        - master
    workflow_dispatch:

jobs:
    premier-job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout 
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with: 
                node-version: '24'
                cache: npm

            - name: Installation 
              run: npm ci 

            - name: Test des vunerabilité 
              run: npm audit && echo "Acune vunerabilité toute est ok ! 👌"